version: "3.8"
services:
  app:
    image: laravel:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork

  mysql:
    image: mysql:8.3.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sys
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - mynetwork

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
